# -*- coding: utf-8 -*-
"""api

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tcOOJjTT-CRIh5V1h7uVVaRW0IS4OYaZ
"""

# app.py

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
import numpy as np
import pickle

# Cargar el modelo
with open("modelo.pkl", "rb") as f:
    model = pickle.load(f)

# Crear la app
app = FastAPI()

# Configurar CORS
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)

# Modelo de entrada
class PatientData(BaseModel):
    age: int
    gender: int
    educationyears: int
    glucose_min: float
    cholesterol_total: float
    EF: float
    PS: float
    Global: float

# Endpoint raíz
@app.get("/")
def home():
    return {"message": "API para predicción de demencia"}

# Endpoint de predicción
@app.post("/predict")
def predict(data: PatientData):
    features = np.array([[
        data.age,
        data.gender,
        data.educationyears,
        data.glucose_min,
        data.cholesterol_total,
        data.EF,
        data.PS,
        data.Global
    ]])
    prediction = model.predict(features)[0]
    return {"prediction": str(prediction)}